// AUTO-GENERATED — npm run exercisedb:catalog
// forme_exercise_catalog.json 기준 nameEn → exerciseDbId
export const FORMÉ_EXERCISE_DB_IDS: Record<string, string> = {
  "3/4 sit-up": "0001",
  "45° side bend": "0002",
  "air bike": "0003",
  "all fours squad stretch": "1512",
  "alternate heel touchers": "0006",
  "alternate lateral pulldown": "0007",
  "ankle circles": "1368",
  "archer pull up": "3293",
  "archer push up": "3294",
  "arm slingers hanging bent knee legs": "2355",
  "arm slingers hanging straight legs": "2333",
  "arms apart circular toe touch (male)": "3214",
  "arms overhead full sit-up (male)": "3204",
  "assisted chest dip (kneeling)": "0009",
  "assisted hanging knee raise": "0011",
  "assisted hanging knee raise with throw down": "0010",
  "assisted lying calves stretch": "1708",
  "assisted lying glutes stretch": "1709",
  "assisted lying gluteus and piriformis stretch": "1710",
  "assisted lying leg raise with lateral throw down": "0012",
  "assisted lying leg raise with throw down": "0013",
  "assisted motion russian twist": "0014",
  "assisted parallel close grip pull-up": "0015",
  "assisted prone hamstring": "0016",
  "assisted prone lying quads stretch": "1713",
  "assisted prone rectus femoris stretch": "1714",
  "assisted pull-up": "0017",
  "assisted seated pectoralis major stretch with stability ball": "1716",
  "assisted side lying adductor stretch": "1712",
  "assisted sit-up": "1758",
  "assisted standing chin-up": "1431",
  "assisted standing pull-up": "1432",
  "assisted standing triceps extension (with towel)": "0018",
  "assisted triceps dip (kneeling)": "0019",
  "assisted wide-grip chest dip (kneeling)": "2364",
  "astride jumps (male)": "3220",
  "back and forth step": "3672",
  "back extension on exercise ball": "1314",
  "back lever": "3297",
  "back pec stretch": "1405",
  "backward jump": "1473",
  "balance board": "0020",
  "band alternating biceps curl": "0968",
  "band alternating v-up": "0969",
  "band assisted pull-up": "0970",
  "band assisted wheel rollerout": "0971",
  "band bench press": "1254",
  "band bent-over hip extension": "0980",
  "band bicycle crunch": "0972",
  "band close-grip pulldown": "0974",
  "band close-grip push-up": "0975",
  "band concentration curl": "0976",
  "band fixed back close grip pulldown": "3117",
  "band fixed back underhand pulldown": "3116",
  "band front lateral raise": "0977",
  "band front raise": "0978",
  "band hip lift": "1408",
  "band horizontal pallof press": "0979",
  "band jack knife sit-up": "0981",
  "band kneeling one arm pulldown": "0983",
  "band kneeling twisting crunch": "0985",
  "band lying hip internal rotation": "0984",
  "band lying straight leg raise": "1002",
  "band one arm overhead biceps curl": "0986",
  "band one arm single leg split squat": "0987",
  "band one arm standing low row": "0988",
  "band one arm twisting chest press": "0989",
  "band one arm twisting seated row": "0990",
  "band pull through": "0991",
  "band push sit-up": "0992",
  "band reverse fly": "0993",
  "band reverse wrist curl": "0994",
  "band seated hip internal rotation": "0996",
  "band seated twist": "1011",
  "band shoulder press": "0997",
  "band shrug": "1018",
  "band side triceps extension": "0998",
  "band single leg calf raise": "0999",
  "band single leg reverse calf raise": "1000",
  "band single leg split squat": "1001",
  "band squat": "1004",
  "band squat row": "1003",
  "band standing crunch": "1005",
  "band standing rear delt row": "1022",
  "band standing twisting crunch": "1007",
  "band step-up": "1008",
  "band stiff leg deadlift": "1009",
  "band straight back stiff leg deadlift": "1023",
  "band straight leg deadlift": "1010",
  "band twisting overhead press": "1012",
  "band two legs calf raise - (band under both legs) v. 2": "1369",
  "band underhand pulldown": "1013",
  "band v-up": "1014",
  "band vertical pallof press": "1015",
  "band wrist curl": "1016",
  "band y-raise": "1017",
  "barbell alternate biceps curl": "0023",
  "barbell bench front squat": "0024",
  "barbell bench press": "0025",
  "barbell bench squat": "0026",
  "barbell bent arm pullover": "1316",
  "barbell bent over row": "0027",
  "barbell biceps curl (with arm blaster)": "2407",
  "barbell clean and press": "0028",
  "barbell clean-grip front squat": "0029",
  "barbell close-grip bench press": "0030",
  "barbell curl": "0031",
  "barbell deadlift": "0032",
  "barbell decline bench press": "0033",
  "barbell decline bent arm pullover": "0034",
  "barbell decline close grip to skull press": "0035",
  "barbell decline pullover": "1255",
  "barbell decline wide-grip press": "0036",
  "barbell decline wide-grip pullover": "0037",
  "barbell drag curl": "0038",
  "barbell floor calf raise": "1370",
  "barbell front chest squat": "0039",
  "barbell front raise": "0041",
  "barbell front raise and pullover": "0040",
  "barbell front squat": "0042",
  "barbell full squat": "0043",
  "barbell full squat (back pov)": "1461",
  "barbell full squat (side pov)": "1462",
  "barbell full zercher squat": "1545",
  "barbell glute bridge": "1409",
  "barbell glute bridge two legs on bench (male)": "3562",
  "barbell good morning": "0044",
  "barbell guillotine bench press": "0045",
  "barbell hack squat": "0046",
  "barbell high bar squat": "1436",
  "barbell incline bench press": "0047",
  "barbell incline close grip bench press": "1719",
  "barbell incline reverse-grip press": "0048",
  "barbell incline row": "0049",
  "barbell incline shoulder raise": "0050",
  "barbell jefferson squat": "0051",
  "barbell jm bench press": "0052",
  "barbell jump squat": "0053",
  "barbell lateral lunge": "1410",
  "barbell low bar squat": "1435",
  "barbell lunge": "0054",
  "barbell lying back of the head tricep extension": "1720",
  "barbell lying close-grip press": "0055",
  "barbell lying close-grip triceps extension": "0056",
  "barbell lying extension": "0057",
  "barbell lying lifting (on hip)": "0058",
  "barbell lying preacher curl": "0059",
  "barbell lying triceps extension": "0061",
  "barbell lying triceps extension skull crusher": "0060",
  "barbell narrow stance squat": "0063",
  "barbell one arm bent over row": "0064",
  "barbell one arm floor press": "0065",
  "barbell one arm side deadlift": "0066",
  "barbell one arm snatch": "0067",
  "barbell one leg squat": "0068",
  "barbell overhead squat": "0069",
  "barbell palms down wrist curl over a bench": "1411",
  "barbell palms up wrist curl over a bench": "1412",
  "barbell pendlay row": "3017",
  "barbell pin presses": "1751",
  "barbell preacher curl": "0070",
  "barbell press sit-up": "0071",
  "barbell prone incline curl": "0072",
  "barbell pullover": "0073",
  "barbell pullover to press": "0022",
  "barbell rack pull": "0074",
  "barbell rear delt raise": "0075",
  "barbell rear delt row": "0076",
  "barbell rear lunge": "0078",
  "barbell rear lunge v. 2": "0077",
  "barbell revers wrist curl v. 2": "0079",
  "barbell reverse close-grip bench press": "2187",
  "barbell reverse curl": "0080",
  "barbell reverse grip bent over row": "0118",
  "barbell reverse grip decline bench press": "1256",
  "barbell reverse grip incline bench press": "1257",
  "barbell reverse grip incline bench row": "1317",
  "barbell reverse grip skullcrusher": "1721",
  "barbell reverse preacher curl": "0081",
  "barbell reverse wrist curl": "0082",
  "barbell rollerout": "0084",
  "barbell rollerout from bench": "0083",
  "barbell romanian deadlift": "0085",
  "barbell seated behind head military press": "0086",
  "barbell seated bradford rocky press": "0087",
  "barbell seated calf raise": "1371",
  "barbell seated close grip behind neck triceps extension": "1718",
  "barbell seated close-grip concentration curl": "0089",
  "barbell seated good morning": "0090",
  "barbell seated overhead press": "0091",
  "barbell seated overhead triceps extension": "0092",
  "barbell seated twist": "0094",
  "barbell shrug": "0095",
  "barbell side bent v. 2": "0096",
  "barbell side split squat": "0098",
  "barbell side split squat v. 2": "0097",
  "barbell single leg deadlift": "1756",
  "barbell single leg split squat": "0099",
  "barbell sitted alternate leg raise": "2799",
  "barbell sitted alternate leg raise (female)": "2800",
  "barbell skier": "0100",
  "barbell speed squat": "0101",
  "barbell split squat v. 2": "2810",
  "barbell squat (on knees)": "0102",
  "barbell squat jump step rear lunge": "2798",
  "barbell standing ab rollerout": "0103",
  "barbell standing back wrist curl": "0104",
  "barbell standing bradford press": "0105",
  "barbell standing calf raise": "1372",
  "barbell standing close grip curl": "0106",
  "barbell standing close grip military press": "1456",
  "barbell standing concentration curl": "2414",
  "barbell standing front raise over head": "0107",
  "barbell standing leg calf raise": "0108",
  "barbell standing overhead triceps extension": "0109",
  "barbell standing reverse grip curl": "0110",
  "barbell standing rocking leg calf raise": "0111",
  "barbell standing twist": "0112",
  "barbell standing wide grip biceps curl": "1629",
  "barbell standing wide military press": "1457",
  "barbell standing wide-grip curl": "0113",
  "barbell step-up": "0114",
  "barbell stiff leg good morning": "0115",
  "barbell straight leg deadlift": "0116",
  "barbell sumo deadlift": "0117",
  "barbell thruster": "3305",
  "barbell upright row": "0120",
  "barbell upright row v. 2": "0119",
  "barbell upright row v. 3": "0121",
  "barbell wide bench press": "0122",
  "barbell wide reverse grip bench press": "1258",
  "barbell wide squat": "0124",
  "barbell wide-grip upright row": "0123",
  "barbell wrist curl": "0126",
  "barbell wrist curl v. 2": "0125",
  "barbell zercher squat": "0127",
  "basic toe touch (male)": "3212",
  "battling ropes": "0128",
  "bear crawl": "3360",
  "behind head chest stretch": "1259",
  "bench dip (knees bent)": "0129",
  "bench dip on floor": "1399",
  "bench hip extension": "0130",
  "bench pull-ups": "3019",
  "bent knee lying twist (male)": "3639",
  "biceps leg concentration curl": "1770",
  "biceps narrow pull-ups": "0139",
  "biceps pull-up": "0140",
  "body-up": "0137",
  "bodyweight drop jump squat": "3543",
  "bodyweight incline side plank": "3544",
  "bodyweight kneeling triceps extension": "1771",
  "bodyweight side lying biceps curl": "1769",
  "bodyweight squatting row": "3168",
  "bodyweight squatting row (with towel)": "3167",
  "bodyweight standing calf raise": "1373",
  "bodyweight standing close-grip one arm row": "3156",
  "bodyweight standing close-grip row": "3158",
  "bodyweight standing one arm row": "3162",
  "bodyweight standing one arm row (with towel)": "3161",
  "bodyweight standing row": "3166",
  "bodyweight standing row (with towel)": "3165",
  "bottoms-up": "0138",
  "box jump down with one leg stabilization": "1374",
  "bridge - mountain climber (cross body)": "2466",
  "burpee": "1160",
  "butt-ups": "0870",
  "butterfly yoga pose": "1494",
  "cable alternate shoulder press": "0148",
  "cable alternate triceps extension": "0149",
  "cable assisted inverse leg curl": "3235",
  "cable bar lateral pulldown": "0150",
  "cable bench press": "0151",
  "cable close grip curl": "1630",
  "cable concentration curl": "1631",
  "cable concentration extension (on knee)": "0152",
  "cable cross-over lateral pulldown": "0153",
  "cable cross-over revers fly": "0154",
  "cable cross-over variation": "0155",
  "cable curl": "0868",
  "cable deadlift": "0157",
  "cable decline fly": "0158",
  "cable decline one arm press": "1260",
  "cable decline press": "1261",
  "cable decline seated wide-grip row": "0159",
  "cable drag curl": "1632",
  "cable floor seated wide-grip row": "0160",
  "cable forward raise": "0161",
  "cable front raise": "0162",
  "cable front shoulder raise": "0164",
  "cable hammer curl (with rope)": "0165",
  "cable high pulley overhead tricep extension": "1722",
  "cable high row (kneeling)": "0167",
  "cable hip adduction": "0168",
  "cable incline bench press": "0169",
  "cable incline bench row": "1318",
  "cable incline fly": "0171",
  "cable incline fly (on stability ball)": "0170",
  "cable incline pushdown": "0172",
  "cable incline triceps extension": "0173",
  "cable judo flip": "0174",
  "cable kickback": "0860",
  "cable kneeling crunch": "0175",
  "cable kneeling rear delt row (with rope) (male)": "3697",
  "cable kneeling triceps extension": "0176",
  "cable lat pulldown full range of motion": "2330",
  "cable lateral pulldown (with rope attachment)": "0177",
  "cable lateral pulldown with v-bar": "2616",
  "cable lateral raise": "0178",
  "cable low fly": "0179",
  "cable low seated row": "0180",
  "cable lying bicep curl": "1634",
  "cable lying close-grip curl": "0182",
  "cable lying extension pullover (with rope attachment)": "0184",
  "cable lying fly": "0185",
  "cable lying triceps extension v. 2": "0186",
  "cable middle fly": "0188",
  "cable one arm bent over row": "0189",
  "cable one arm curl": "0190",
  "cable one arm decline chest fly": "1262",
  "cable one arm fly on exercise ball": "1263",
  "cable one arm incline fly on exercise ball": "1264",
  "cable one arm incline press": "1265",
  "cable one arm incline press on exercise ball": "1266",
  "cable one arm lateral bent-over": "0191",
  "cable one arm lateral raise": "0192",
  "cable one arm preacher curl": "1633",
  "cable one arm press on exercise ball": "1267",
  "cable one arm pulldown": "3563",
  "cable one arm reverse preacher curl": "1635",
  "cable one arm straight back high row (kneeling)": "0193",
  "cable one arm tricep pushdown": "1723",
  "cable overhead curl": "1636",
  "cable overhead curl on exercise ball": "1637",
  "cable overhead triceps extension (rope attachment)": "0194",
  "cable palm rotational row": "1319",
  "cable preacher curl": "0195",
  "cable press on exercise ball": "1268",
  "cable pull through (with rope)": "0196",
  "cable pulldown": "0198",
  "cable pulldown (pro lat bar)": "0197",
  "cable pulldown bicep curl": "1638",
  "cable pushdown": "0201",
  "cable pushdown (straight arm) v. 2": "0199",
  "cable pushdown (with rope attachment)": "0200",
  "cable rear delt row (stirrups)": "0202",
  "cable rear delt row (with rope)": "0203",
  "cable rear drive": "0204",
  "cable rear pulldown": "0205",
  "cable reverse crunch": "0873",
  "cable reverse curl": "0206",
  "cable reverse grip triceps pushdown (sz-bar) (with arm blaster)": "2406",
  "cable reverse one arm curl": "1413",
  "cable reverse preacher curl": "0209",
  "cable reverse wrist curl": "0210",
  "cable reverse-grip pushdown": "0207",
  "cable reverse-grip straight back seated high row": "0208",
  "cable rope crossover seated row": "1320",
  "cable rope elevated seated row": "1321",
  "cable rope extension incline bench row": "1322",
  "cable rope hammer preacher curl": "1639",
  "cable rope high pulley overhead tricep extension": "1724",
  "cable rope incline tricep extension": "1725",
  "cable rope lying on floor tricep extension": "1726",
  "cable rope one arm hammer preacher curl": "1640",
  "cable rope seated row": "1323",
  "cable russian twists (on stability ball)": "0211",
  "cable seated chest press": "2144",
  "cable seated crunch": "0212",
  "cable seated curl": "1641",
  "cable seated high row (v-bar)": "0213",
  "cable seated one arm alternate row": "0214",
  "cable seated one arm concentration curl": "1642",
  "cable seated overhead curl": "1643",
  "cable seated rear lateral raise": "0215",
  "cable seated row": "0861",
  "cable seated shoulder internal rotation": "0216",
  "cable seated twist": "2399",
  "cable seated wide-grip row": "0218",
  "cable shoulder press": "0219",
  "cable shrug": "0220",
  "cable side bend": "0222",
  "cable side bend crunch (bosu ball)": "0221",
  "cable side crunch": "0223",
  "cable squat row (with rope attachment)": "1717",
  "cable squatting curl": "1644",
  "cable standing back wrist curl": "0224",
  "cable standing calf raise": "1375",
  "cable standing cross-over high reverse fly": "0225",
  "cable standing crunch": "0226",
  "cable standing crunch (with rope attachment)": "0874",
  "cable standing fly": "0227",
  "cable standing hip extension": "0228",
  "cable standing inner curl": "0229",
  "cable standing lift": "0230",
  "cable standing one arm triceps extension": "0231",
  "cable standing one leg calf raise": "1376",
  "cable standing pulldown (with rope)": "0232",
  "cable standing rear delt row (with rope)": "0233",
  "cable standing reverse grip one arm overhead tricep extension": "1727",
  "cable standing row (v-bar)": "0234",
  "cable standing shoulder external rotation": "0235",
  "cable standing twist row (v-bar)": "0236",
  "cable standing up straight crossovers": "1269",
  "cable straight arm pulldown": "0238",
  "cable straight arm pulldown (with rope)": "0237",
  "cable straight back seated row": "0239",
  "cable supine reverse fly": "0240",
  "cable thibaudeau kayak row": "2464",
  "cable triceps pushdown (v-bar)": "0241",
  "cable triceps pushdown (v-bar) (with arm blaster)": "2405",
  "cable tuck reverse crunch": "0242",
  "cable twist": "0243",
  "cable twist (up-down)": "0862",
  "cable twisting pull": "0244",
  "cable two arm curl on incline bench": "1645",
  "cable two arm tricep kickback": "1728",
  "cable underhand pulldown": "0245",
  "cable upper chest crossovers": "1270",
  "cable upper row": "1324",
  "cable upright row": "0246",
  "cable wide grip rear pulldown behind neck": "1325",
  "cable wrist curl": "0247",
  "calf push stretch with hands against wall": "1407",
  "calf stretch with hands against wall": "1377",
  "calf stretch with rope": "1378",
  "cambered bar lying row": "0248",
  "captains chair straight leg raise": "2963",
  "chair leg extended stretch": "1548",
  "chest and front of shoulder stretch": "1271",
  "chest dip": "0251",
  "chest dip (on dip-pull-up cage)": "1430",
  "chest dip on straight bar": "2462",
  "chest stretch with exercise ball": "1272",
  "chest tap push-up (male)": "3216",
  "chin-up": "1326",
  "chin-ups (narrow parallel grip)": "0253",
  "circles knee stretch": "0257",
  "clap push up": "1273",
  "clock push-up": "0258",
  "close grip chin-up": "1327",
  "close-grip push-up": "0259",
  "close-grip push-up (on knees)": "2398",
  "cocoons": "0260",
  "crab twist toe touch": "1468",
  "cross body crunch": "0262",
  "crunch (hands overhead)": "0267",
  "crunch (on stability ball, arms straight)": "0272",
  "crunch (on stability ball)": "0271",
  "crunch floor": "0274",
  "curl-up": "3016",
  "curtsey squat": "3769",
  "cycle cross trainer": "2331",
  "dead bug": "0276",
  "decline crunch": "0277",
  "decline push-up": "0279",
  "decline sit-up": "0282",
  "deep push up": "1274",
  "diamond push-up": "0283",
  "donkey calf raise": "0284",
  "drop push up": "1275",
  "dumbbell alternate biceps curl": "0285",
  "dumbbell alternate biceps curl (with arm blaster)": "2403",
  "dumbbell alternate hammer preacher curl": "1646",
  "dumbbell alternate preacher curl": "1647",
  "dumbbell alternate seated hammer curl": "1648",
  "dumbbell alternate side press": "0286",
  "dumbbell alternating bicep curl with leg raised on exercise ball": "1649",
  "dumbbell alternating seated bicep curl on exercise ball": "1650",
  "dumbbell arnold press": "2137",
  "dumbbell arnold press v. 2": "0287",
  "dumbbell around pullover": "0288",
  "dumbbell bench press": "0289",
  "dumbbell bench seated press": "0290",
  "dumbbell bench squat": "0291",
  "dumbbell bent over row": "0293",
  "dumbbell bicep curl lunge with bowling motion": "1651",
  "dumbbell bicep curl on exercise ball with leg raised": "1652",
  "dumbbell bicep curl with stork stance": "1653",
  "dumbbell biceps curl": "0294",
  "dumbbell biceps curl (with arm blaster)": "2401",
  "dumbbell biceps curl reverse": "1654",
  "dumbbell biceps curl squat": "1655",
  "dumbbell biceps curl v sit on bosu ball": "1656",
  "dumbbell burpee": "1201",
  "dumbbell clean": "0295",
  "dumbbell close grip press": "1731",
  "dumbbell close-grip press": "0296",
  "dumbbell concentration curl": "0297",
  "dumbbell contralateral forward lunge": "3635",
  "dumbbell cross body hammer curl": "0298",
  "dumbbell cross body hammer curl v. 2": "1657",
  "dumbbell cuban press": "0299",
  "dumbbell cuban press v. 2": "2136",
  "dumbbell deadlift": "0300",
  "dumbbell decline bench press": "0301",
  "dumbbell decline fly": "0302",
  "dumbbell decline hammer press": "0303",
  "dumbbell decline one arm fly": "1276",
  "dumbbell decline one arm hammer press": "1617",
  "dumbbell decline shrug": "0305",
  "dumbbell decline shrug v. 2": "0304",
  "dumbbell decline triceps extension": "0306",
  "dumbbell decline twist fly": "0307",
  "dumbbell finger curls": "1437",
  "dumbbell fly": "0308",
  "dumbbell fly on exercise ball": "1277",
  "dumbbell forward lunge triceps extension": "1732",
  "dumbbell front raise": "0310",
  "dumbbell front raise v. 2": "0309",
  "dumbbell full can lateral raise": "0311",
  "dumbbell goblet squat": "1760",
  "dumbbell hammer curl": "0313",
  "dumbbell hammer curl on exercise ball": "1659",
  "dumbbell hammer curl v. 2": "0312",
  "dumbbell hammer curls (with arm blaster)": "2402",
  "dumbbell high curl": "1664",
  "dumbbell incline alternate press": "3545",
  "dumbbell incline bench press": "0314",
  "dumbbell incline biceps curl": "0315",
  "dumbbell incline breeding": "0316",
  "dumbbell incline curl": "0318",
  "dumbbell incline curl v. 2": "0317",
  "dumbbell incline fly": "0319",
  "dumbbell incline fly on exercise ball": "1278",
  "dumbbell incline hammer curl": "0320",
  "dumbbell incline hammer press": "0321",
  "dumbbell incline hammer press on exercise ball": "1618",
  "dumbbell incline inner biceps curl": "0322",
  "dumbbell incline one arm fly": "1279",
  "dumbbell incline one arm fly on exercise ball": "1280",
  "dumbbell incline one arm hammer press": "1619",
  "dumbbell incline one arm hammer press on exercise ball": "1620",
  "dumbbell incline one arm lateral raise": "0323",
  "dumbbell incline one arm press": "1281",
  "dumbbell incline one arm press on exercise ball": "1282",
  "dumbbell incline palm-in press": "0324",
  "dumbbell incline press on exercise ball": "1283",
  "dumbbell incline raise": "0325",
  "dumbbell incline rear lateral raise": "0326",
  "dumbbell incline row": "0327",
  "dumbbell incline shoulder raise": "0328",
  "dumbbell incline shrug": "0329",
  "dumbbell incline t-raise": "3542",
  "dumbbell incline triceps extension": "0330",
  "dumbbell incline twisted flyes": "0331",
  "dumbbell incline two arm extension": "1733",
  "dumbbell incline y-raise": "3541",
  "dumbbell iron cross": "0332",
  "dumbbell kickback": "0333",
  "dumbbell kickbacks on exercise ball": "1734",
  "dumbbell kneeling bicep curl exercise ball": "1660",
  "dumbbell lateral raise": "0334",
  "dumbbell lateral to front raise": "0335",
  "dumbbell lunge": "0336",
  "dumbbell lunge with bicep curl": "1658",
  "dumbbell lying alternate extension": "1729",
  "dumbbell lying elbow press": "0338",
  "dumbbell lying extension (across face)": "0337",
  "dumbbell lying external shoulder rotation": "0863",
  "dumbbell lying femoral": "0339",
  "dumbbell lying hammer press": "0340",
  "dumbbell lying on floor rear delt raise": "2470",
  "dumbbell lying one arm deltoid rear": "0341",
  "dumbbell lying one arm press": "0343",
  "dumbbell lying one arm press v. 2": "0342",
  "dumbbell lying one arm pronated triceps extension": "0344",
  "dumbbell lying one arm rear lateral raise": "0345",
  "dumbbell lying one arm supinated triceps extension": "0346",
  "dumbbell lying pronation": "0347",
  "dumbbell lying pronation on floor": "2705",
  "dumbbell lying pullover on exercise ball": "1284",
  "dumbbell lying rear delt row": "1328",
  "dumbbell lying rear lateral raise": "0348",
  "dumbbell lying single extension": "1735",
  "dumbbell lying supination": "0349",
  "dumbbell lying supination on floor": "2706",
  "dumbbell lying supine biceps curl": "1661",
  "dumbbell lying supine curl": "0350",
  "dumbbell lying triceps extension": "0351",
  "dumbbell lying wide curl": "1662",
  "dumbbell neutral grip bench press": "0352",
  "dumbbell one arm bench fly": "1285",
  "dumbbell one arm bent-over row": "0292",
  "dumbbell one arm chest fly on exercise ball": "1286",
  "dumbbell one arm concentration curl (on stability ball)": "0353",
  "dumbbell one arm decline chest press": "1287",
  "dumbbell one arm fly on exercise ball": "1288",
  "dumbbell one arm french press on exercise ball": "1736",
  "dumbbell one arm hammer preacher curl": "1663",
  "dumbbell one arm hammer press on exercise ball": "1621",
  "dumbbell one arm incline chest press": "1289",
  "dumbbell one arm kickback": "0354",
  "dumbbell one arm lateral raise": "0355",
  "dumbbell one arm lateral raise with support": "0356",
  "dumbbell one arm press on exercise ball": "1290",
  "dumbbell one arm prone curl": "1665",
  "dumbbell one arm prone hammer curl": "1666",
  "dumbbell one arm pullover on exercise ball": "1291",
  "dumbbell one arm reverse fly (with support)": "0359",
  "dumbbell one arm reverse grip press": "1622",
  "dumbbell one arm reverse preacher curl": "1414",
  "dumbbell one arm reverse spider curl": "1667",
  "dumbbell one arm reverse wrist curl": "0358",
  "dumbbell one arm seated bicep curl on exercise ball": "1668",
  "dumbbell one arm seated hammer curl": "1669",
  "dumbbell one arm seated neutral wrist curl": "1415",
  "dumbbell one arm shoulder press": "0361",
  "dumbbell one arm shoulder press v. 2": "0360",
  "dumbbell one arm snatch": "3888",
  "dumbbell one arm standing curl": "1670",
  "dumbbell one arm standing hammer curl": "1671",
  "dumbbell one arm triceps extension (on bench)": "0362",
  "dumbbell one arm upright row": "0363",
  "dumbbell one arm wrist curl": "0364",
  "dumbbell one arm zottman preacher curl": "1672",
  "dumbbell one leg fly on exercise ball": "1292",
  "dumbbell over bench neutral wrist curl": "0365",
  "dumbbell over bench one arm neutral wrist curl": "0366",
  "dumbbell over bench one arm reverse wrist curl": "1441",
  "dumbbell over bench one arm wrist curl": "0367",
  "dumbbell over bench revers wrist curl": "0368",
  "dumbbell over bench wrist curl": "0369",
  "dumbbell palm rotational bent over row": "1329",
  "dumbbell palms in incline bench press": "1623",
  "dumbbell peacher hammer curl": "0370",
  "dumbbell plyo squat": "0371",
  "dumbbell preacher curl": "0372",
  "dumbbell preacher curl over exercise ball": "1673",
  "dumbbell press on exercise ball": "1293",
  "dumbbell pronate-grip triceps extension": "0373",
  "dumbbell prone incline curl": "0374",
  "dumbbell prone incline hammer curl": "1674",
  "dumbbell pullover": "0375",
  "dumbbell pullover hip extension on exercise ball": "1294",
  "dumbbell pullover on exercise ball": "1295",
  "dumbbell push press": "1700",
  "dumbbell raise": "0376",
  "dumbbell rear delt raise": "2292",
  "dumbbell rear delt row_shoulder": "0377",
  "dumbbell rear fly": "0378",
  "dumbbell rear lateral raise": "0380",
  "dumbbell rear lateral raise (support head)": "0379",
  "dumbbell rear lunge": "0381",
  "dumbbell revers grip biceps curl": "0382",
  "dumbbell reverse bench press": "1624",
  "dumbbell reverse fly": "0383",
  "dumbbell reverse grip incline bench one arm row": "1330",
  "dumbbell reverse grip incline bench two arm row": "1331",
  "dumbbell reverse grip row (female)": "2327",
  "dumbbell reverse preacher curl": "0384",
  "dumbbell reverse spider curl": "1675",
  "dumbbell reverse wrist curl": "0385",
  "dumbbell romanian deadlift": "1459",
  "dumbbell rotation reverse fly": "0386",
  "dumbbell scott press": "2397",
  "dumbbell seated alternate front raise": "0387",
  "dumbbell seated alternate hammer curl on exercise ball": "1676",
  "dumbbell seated alternate press": "0388",
  "dumbbell seated alternate shoulder": "3546",
  "dumbbell seated bench extension": "0389",
  "dumbbell seated bent arm lateral raise": "2317",
  "dumbbell seated bent over alternate kickback": "1730",
  "dumbbell seated bent over triceps extension": "1737",
  "dumbbell seated bicep curl": "1677",
  "dumbbell seated biceps curl (on stability ball)": "0390",
  "dumbbell seated biceps curl to shoulder press": "3547",
  "dumbbell seated calf raise": "1379",
  "dumbbell seated curl": "0391",
  "dumbbell seated front raise": "0392",
  "dumbbell seated hammer curl": "1678",
  "dumbbell seated inner biceps curl": "0393",
  "dumbbell seated kickback": "0394",
  "dumbbell seated lateral raise": "0396",
  "dumbbell seated lateral raise v. 2": "0395",
  "dumbbell seated neutral wrist curl": "0397",
  "dumbbell seated one arm bicep curl on exercise ball with leg raised": "1679",
  "dumbbell seated one arm kickback": "0398",
  "dumbbell seated one arm rotate": "0399",
  "dumbbell seated one leg calf raise": "0400",
  "dumbbell seated one leg calf raise - hammer grip": "1380",
  "dumbbell seated one leg calf raise - palm up": "1381",
  "dumbbell seated palms up wrist curl": "0401",
  "dumbbell seated preacher curl": "0402",
  "dumbbell seated revers grip concentration curl": "0403",
  "dumbbell seated reverse grip one arm overhead tricep extension": "1738",
  "dumbbell seated shoulder press": "0405",
  "dumbbell seated shoulder press (parallel grip)": "0404",
  "dumbbell seated triceps extension": "2188",
  "dumbbell shrug": "0406",
  "dumbbell side bend": "0407",
  "dumbbell side lying one hand raise": "0408",
  "dumbbell side plank with rear fly": "3664",
  "dumbbell single arm overhead carry": "3548",
  "dumbbell single leg calf raise": "0409",
  "dumbbell single leg deadlift": "1757",
  "dumbbell single leg deadlift with stepbox support": "2805",
  "dumbbell single leg split squat": "0410",
  "dumbbell single leg squat": "0411",
  "dumbbell squat": "0413",
  "dumbbell standing alternate hammer curl and press": "3560",
  "dumbbell standing alternate overhead press": "0414",
  "dumbbell standing alternate raise": "0415",
  "dumbbell standing alternating tricep kickback": "1739",
  "dumbbell standing around world": "2143",
  "dumbbell standing bent over one arm triceps extension": "1740",
  "dumbbell standing bent over two arm triceps extension": "1741",
  "dumbbell standing biceps curl": "0416",
  "dumbbell standing calf raise": "0417",
  "dumbbell standing concentration curl": "0418",
  "dumbbell standing front raise above head": "0419",
  "dumbbell standing inner biceps curl v. 2": "2321",
  "dumbbell standing kickback": "0420",
  "dumbbell standing one arm concentration curl": "0421",
  "dumbbell standing one arm curl (over incline bench)": "0422",
  "dumbbell standing one arm curl over incline bench": "1680",
  "dumbbell standing one arm extension": "0423",
  "dumbbell standing one arm palm in press": "0424",
  "dumbbell standing one arm reverse curl": "0425",
  "dumbbell standing overhead press": "0426",
  "dumbbell standing palms in press": "0427",
  "dumbbell standing preacher curl": "0428",
  "dumbbell standing reverse curl": "0429",
  "dumbbell standing triceps extension": "0430",
  "dumbbell standing zottman preacher curl": "2293",
  "dumbbell step up single leg balance with bicep curl": "1684",
  "dumbbell step-up": "0431",
  "dumbbell step-up lunge": "2796",
  "dumbbell step-up split squat": "2812",
  "dumbbell stiff leg deadlift": "0432",
  "dumbbell straight arm pullover": "0433",
  "dumbbell straight leg deadlift": "0434",
  "dumbbell sumo pull through": "2808",
  "dumbbell supported squat": "2803",
  "dumbbell tate press": "0436",
  "dumbbell tricep kickback with stork stance": "1742",
  "dumbbell twisting bench press": "1743",
  "dumbbell upright row": "0437",
  "dumbbell upright row (back pov)": "1765",
  "dumbbell upright shoulder external rotation": "0864",
  "dumbbell w-press": "0438",
  "dumbbell waiter biceps curl": "5201",
  "dumbbell zottman curl": "0439",
  "dumbbell zottman preacher curl": "2294",
  "dumbbells seated triceps extension": "2189",
  "dynamic chest stretch (male)": "1167",
  "elbow dips": "3287",
  "elbow lift - reverse push-up": "1772",
  "elbow-to-knee": "0443",
  "elevator": "3292",
  "exercise ball alternating arm ups": "1332",
  "exercise ball back extension with arms extended": "1333",
  "exercise ball back extension with hands behind head": "1334",
  "exercise ball back extension with knees off ground": "1335",
  "exercise ball back extension with rotation": "1336",
  "exercise ball dip": "1744",
  "exercise ball hip flexor stretch": "1559",
  "exercise ball hug": "1338",
  "exercise ball lat stretch": "1339",
  "exercise ball lower back stretch (pyramid)": "1341",
  "exercise ball lying side lat stretch": "1342",
  "exercise ball on the wall calf raise": "1382",
  "exercise ball on the wall calf raise (tennis ball between ankles)": "3241",
  "exercise ball on the wall calf raise (tennis ball between knees)": "3240",
  "exercise ball one leg prone lower body rotation": "1416",
  "exercise ball one legged diagonal kick hamstring curl": "1417",
  "exercise ball pike push up": "1296",
  "exercise ball prone leg raise": "1343",
  "exercise ball seated hamstring stretch": "1560",
  "exercise ball seated triceps stretch": "1745",
  "exercise ball supine triceps extension": "1746",
  "ez bar french press on exercise ball": "1747",
  "ez bar lying bent arms pullover": "3010",
  "ez bar lying close grip triceps extension behind head": "1748",
  "ez bar reverse grip bent over row": "1344",
  "ez bar seated close grip concentration curl": "1682",
  "ez bar standing french press": "1749",
  "ez barbell anti gravity press": "0445",
  "ez barbell close grip preacher curl": "1627",
  "ez barbell close-grip curl": "0446",
  "ez barbell curl": "0447",
  "ez barbell decline close grip face press": "0448",
  "ez barbell decline triceps extension": "2186",
  "ez barbell incline triceps extension": "0449",
  "ez barbell jm bench press": "0450",
  "ez barbell reverse grip curl": "0451",
  "ez barbell reverse grip preacher curl": "0452",
  "ez barbell seated curls": "1458",
  "ez barbell seated triceps extension": "0453",
  "ez barbell spider curl": "1628",
  "ez-bar biceps curl (with arm blaster)": "2404",
  "ez-bar close-grip bench press": "2432",
  "ez-barbell standing wide grip biceps curl": "2741",
  "farmers walk": "2133",
  "finger curls": "0455",
  "flag": "3303",
  "flexion leg sit up (bent knee)": "0456",
  "flexion leg sit up (straight arm)": "0457",
  "floor fly (with barbell)": "0458",
  "flutter kicks": "0459",
  "forward jump": "1472",
  "forward lunge (male)": "3470",
  "frankenstein squat": "3194",
  "frog crunch": "2429",
  "frog planche": "3301",
  "front lever": "3296",
  "front lever reps": "3295",
  "front plank with twist": "0464",
  "full maltese": "3315",
  "full planche": "3299",
  "full planche push-up": "3327",
  "gironda sternum chin": "0466",
  "glute bridge march": "3561",
  "glute bridge two legs on bench (male)": "3523",
  "glute-ham raise": "3193",
  "gorilla chin": "0467",
  "groin crunch": "0469",
  "hack calf raise": "1383",
  "hack one leg calf raise": "1384",
  "half knee bends (male)": "3221",
  "half sit-up (male)": "3202",
  "hamstring stretch": "1511",
  "hands bike": "2139",
  "hands clasped circular toe touch (male)": "3218",
  "hands reversed clasped circular toe touch (male)": "3215",
  "handstand": "3302",
  "handstand push-up": "0471",
  "hanging leg hip raise": "1764",
  "hanging leg raise": "0472",
  "hanging oblique knee raise": "1761",
  "hanging pike": "0473",
  "hanging straight leg hip raise": "0474",
  "hanging straight leg raise": "0475",
  "hanging straight twisting leg hip raise": "0476",
  "high knee against wall": "3636",
  "hip raise (bent knee)": "0484",
  "hug keens to chest": "1418",
  "hyght dumbbell fly": "3234",
  "hyperextension": "0489",
  "hyperextension (on bench)": "0488",
  "impossible dips": "3289",
  "inchworm": "1471",
  "inchworm v. 2": "3698",
  "incline close-grip push-up": "0490",
  "incline leg hip raise (leg straight)": "0491",
  "incline push up depth jump": "0492",
  "incline push-up": "0493",
  "incline push-up (on box)": "3785",
  "incline reverse grip push-up": "0494",
  "incline scapula push up": "3011",
  "incline twisting sit-up": "0495",
  "intermediate hip flexor and quad stretch": "1564",
  "inverse leg curl (bench support)": "0496",
  "inverse leg curl (on pull-up cable machine)": "2400",
  "inverted row": "0499",
  "inverted row bent knees": "2300",
  "inverted row on bench": "2298",
  "inverted row v. 2": "0497",
  "inverted row with straps": "0498",
  "iron cross stretch": "1419",
  "isometric chest squeeze": "1297",
  "isometric wipers": "0500",
  "jack burpee": "0501",
  "jack jump (male)": "3224",
  "jackknife sit-up": "0507",
  "janda sit-up": "0508",
  "jump rope": "2612",
  "jump squat": "0514",
  "jump squat v. 2": "0513",
  "kettlebell advanced windmill": "0517",
  "kettlebell alternating hang clean": "0518",
  "kettlebell alternating press": "0520",
  "kettlebell alternating press on floor": "0519",
  "kettlebell alternating renegade row": "0521",
  "kettlebell alternating row": "0522",
  "kettlebell arnold press": "0523",
  "kettlebell bent press": "0524",
  "kettlebell bottoms up clean from the hang position": "0525",
  "kettlebell double alternating hang clean": "0526",
  "kettlebell double jerk": "0527",
  "kettlebell double push press": "0528",
  "kettlebell double snatch": "0529",
  "kettlebell double windmill": "0530",
  "kettlebell extended range one arm press on floor": "0531",
  "kettlebell figure 8": "0532",
  "kettlebell front squat": "0533",
  "kettlebell goblet squat": "0534",
  "kettlebell hang clean": "0535",
  "kettlebell lunge pass through": "0536",
  "kettlebell one arm clean and jerk": "0537",
  "kettlebell one arm floor press": "1298",
  "kettlebell one arm jerk": "0538",
  "kettlebell one arm military press to the side": "0539",
  "kettlebell one arm push press": "0540",
  "kettlebell one arm row": "0541",
  "kettlebell one arm snatch": "0542",
  "kettlebell pirate supper legs": "0543",
  "kettlebell pistol squat": "0544",
  "kettlebell plyo push-up": "0545",
  "kettlebell seated press": "0546",
  "kettlebell seated two arm military press": "1438",
  "kettlebell seesaw press": "0547",
  "kettlebell sumo high pull": "0548",
  "kettlebell swing": "0549",
  "kettlebell thruster": "0550",
  "kettlebell turkish get up (squat style)": "0551",
  "kettlebell two arm clean": "0552",
  "kettlebell two arm military press": "0553",
  "kettlebell two arm row": "1345",
  "kettlebell windmill": "0554",
  "kick out sit": "0555",
  "kipping muscle up": "0558",
  "knee touch crunch": "3640",
  "kneeling jump squat": "1420",
  "kneeling lat stretch": "1346",
  "kneeling plank tap shoulder (male)": "3239",
  "kneeling push-up (male)": "3211",
  "korean dips": "3288",
  "l-pull-up": "3418",
  "l-sit on floor": "3419",
  "landmine 180": "0562",
  "landmine lateral raise": "3237",
  "lean planche": "3300",
  "left hook. boxing": "2271",
  "leg pull in flat bench": "0570",
  "leg up hamstring stretch": "1576",
  "lever alternate leg press": "2287",
  "lever alternating narrow grip seated row": "0571",
  "lever assisted chin-up": "0572",
  "lever back extension": "0573",
  "lever bent over row": "0574",
  "lever bent-over row with v-bar": "3200",
  "lever bicep curl": "0575",
  "lever calf press": "2289",
  "lever chest press": "0576",
  "lever deadlift": "0578",
  "lever decline chest press": "1300",
  "lever donkey calf raise": "1253",
  "lever front pulldown": "0579",
  "lever gripless shrug": "0580",
  "lever gripless shrug v. 2": "1439",
  "lever gripper hands": "2288",
  "lever hammer grip preacher curl": "1615",
  "lever high row": "0581",
  "lever hip extension v. 2": "2286",
  "lever horizontal one leg press": "2611",
  "lever incline chest press": "1299",
  "lever incline chest press v. 2": "1479",
  "lever kneeling leg curl": "0582",
  "lever kneeling twist": "0583",
  "lever lateral raise": "0584",
  "lever leg extension": "0585",
  "lever lying leg curl": "0586",
  "lever lying two-one leg curl": "3195",
  "lever military press": "0587",
  "lever narrow grip seated row": "0588",
  "lever one arm bent over row": "0589",
  "lever one arm lateral high row": "1356",
  "lever one arm lateral wide pulldown": "1347",
  "lever one arm shoulder press": "0590",
  "lever overhand triceps dip": "0591",
  "lever preacher curl": "0592",
  "lever preacher curl v. 2": "1614",
  "lever pullover": "2285",
  "lever reverse grip lateral pulldown": "2736",
  "lever reverse grip preacher curl": "1616",
  "lever reverse grip vertical row": "1348",
  "lever reverse hyperextension": "0593",
  "lever reverse t-bar row": "1349",
  "lever rotary calf": "2315",
  "lever seated calf press": "2335",
  "lever seated calf raise": "0594",
  "lever seated crunch": "1452",
  "lever seated crunch (chest pad)": "0595",
  "lever seated crunch v. 2": "3760",
  "lever seated dip": "1451",
  "lever seated fly": "0596",
  "lever seated good morning": "3759",
  "lever seated hip abduction": "0597",
  "lever seated hip adduction": "0598",
  "lever seated leg curl": "0599",
  "lever seated leg raise crunch": "0600",
  "lever seated reverse fly": "0602",
  "lever seated reverse fly (parallel grip)": "0601",
  "lever seated row": "1350",
  "lever seated squat calf raise on leg press machine": "1385",
  "lever shoulder press": "0603",
  "lever shoulder press v. 2": "0869",
  "lever shoulder press v. 3": "2318",
  "lever shrug": "0604",
  "lever standing calf raise": "0605",
  "lever standing chest press": "3758",
  "lever t bar row": "0606",
  "lever t-bar reverse grip row": "1351",
  "lever triceps extension": "0607",
  "lever unilateral row": "1313",
  "london bridge": "0609",
  "low glute bridge on floor": "3013",
  "lower back curl": "1352",
  "lunge with jump": "3582",
  "lunge with twist": "1688",
  "lying (side) quads stretch": "0613",
  "lying elbow to knee": "2312",
  "lying leg raise flat bench": "0620",
  "lying leg-hip raise": "0865",
  "machine inner chest press": "1301",
  "march sit (wall)": "0624",
  "medicine ball catch and overhead throw": "1353",
  "medicine ball chest pass": "1302",
  "medicine ball chest push from 3 point stance": "1303",
  "medicine ball chest push multiple response": "1304",
  "medicine ball chest push single response": "1305",
  "medicine ball chest push with run release": "1312",
  "medicine ball close grip push up": "1701",
  "medicine ball overhead slam": "1354",
  "medicine ball supine chest throw": "1750",
  "mixed grip chin-up": "0627",
  "modified hindu push-up (male)": "3217",
  "modified push up to lower arms": "1421",
  "monster walk": "0628",
  "mountain climber": "0630",
  "muscle up": "0631",
  "muscle-up (on vertical bar)": "1401",
  "narrow push-up on exercise ball": "2328",
  "neck side stretch": "1403",
  "negative crunch": "0634",
  "oblique crunch v. 2": "1495",
  "oblique crunches floor": "0635",
  "olympic barbell hammer curl": "0636",
  "olympic barbell triceps extension": "0637",
  "one arm against wall": "1355",
  "one arm chin-up": "0638",
  "one arm dip": "0639",
  "one arm slam (with medicine ball)": "0640",
  "one arm towel row": "1773",
  "one leg donkey calf raise": "1386",
  "one leg floor calf raise": "1387",
  "one leg squat": "1476",
  "otis up": "0641",
  "outside leg kick push-up": "0642",
  "overhead triceps stretch": "0643",
  "pelvic tilt": "3147",
  "pelvic tilt into bridge": "1422",
  "peroneals stretch": "1388",
  "pike-to-cobra push-up": "3662",
  "plyo push up": "1306",
  "posterior step to overhead reach": "1687",
  "posterior tibialis stretch": "1389",
  "potty squat": "3119",
  "potty squat with support": "3132",
  "power clean": "0648",
  "power point plank": "3665",
  "prisoner half sit-up (male)": "3203",
  "prone twist on stability ball": "1707",
  "pull up (neutral grip)": "0651",
  "pull-in (on stability ball)": "0650",
  "pull-up": "0652",
  "push and pull bodyweight": "1689",
  "push to run": "3638",
  "push up on bosu ball": "1307",
  "push-up": "0662",
  "push-up (bosu ball)": "0653",
  "push-up (on stability ball)": "0656",
  "push-up (wall)": "0659",
  "push-up (wall) v. 2": "0658",
  "push-up close-grip off dumbbell": "0660",
  "push-up inside leg kick": "0661",
  "push-up medicine ball": "0663",
  "push-up on lower arms": "1467",
  "push-up plus": "3145",
  "push-up to side plank": "0664",
  "quads": "3533",
  "quarter sit-up": "3201",
  "quick feet v. 2": "3552",
  "raise single arm push-up": "0666",
  "rear decline bridge": "0668",
  "rear deltoid stretch": "0669",
  "rear pull-up": "0670",
  "reclining big toe pose with rope": "1582",
  "resistance band hip thrusts on knees (female)": "3236",
  "resistance band leg extension": "3007",
  "resistance band seated biceps curl": "3123",
  "resistance band seated chest press": "3124",
  "resistance band seated hip abduction": "3006",
  "resistance band seated shoulder press": "3122",
  "resistance band seated straight back row": "3144",
  "reverse crunch": "0872",
  "reverse dip": "0672",
  "reverse grip machine lat pulldown": "0673",
  "reverse grip pull-up": "0674",
  "reverse hyper extension (on stability ball)": "0675",
  "reverse hyper on flat bench": "1423",
  "reverse plank with leg lift": "3663",
  "ring dips": "0677",
  "rocking frog stretch": "2571",
  "rocky pull-up pulldown": "0678",
  "roller back stretch": "2208",
  "roller body saw": "2204",
  "roller hip lat stretch": "2205",
  "roller hip stretch": "2202",
  "roller reverse crunch": "2206",
  "roller seated shoulder flexor depresor retractor": "2203",
  "roller seated single leg shoulder flexor depresor retractor": "2209",
  "roller side lat stretch": "2207",
  "rope climb": "0680",
  "run": "0685",
  "run (equipment)": "0684",
  "runners stretch": "1585",
  "russian twist": "0687",
  "scapula dips": "3012",
  "scapula push-up": "3021",
  "scapular pull-up": "0688",
  "scissor jumps (male)": "3219",
  "seated calf stretch (male)": "1390",
  "seated glute stretch": "1424",
  "seated leg raise": "0689",
  "seated lower back stretch": "0690",
  "seated piriformis stretch": "2567",
  "seated side crunch (wall)": "0691",
  "seated wide angle pose sequence": "1587",
  "self assisted inverse leg curl": "1766",
  "self assisted inverse leg curl (on floor)": "0696",
  "semi squat jump (male)": "3222",
  "short stride run": "3656",
  "shoulder grip pull-up": "1763",
  "shoulder tap": "3699",
  "shoulder tap push-up": "0699",
  "side bridge hip abduction": "1774",
  "side bridge v. 2": "0705",
  "side hip (on parallel bars)": "0709",
  "side hip abduction": "0710",
  "side lying floor stretch": "1358",
  "side lying hip adduction (male)": "3667",
  "side plank hip adduction": "1775",
  "side push neck stretch": "0716",
  "side push-up": "0717",
  "side wrist pull stretch": "0721",
  "side-to-side chin": "0720",
  "side-to-side toe touch (male)": "3213",
  "single arm push-up": "0725",
  "single leg bridge with outstretched leg": "3645",
  "single leg calf raise (on a dumbbell)": "0727",
  "single leg platform slide": "0730",
  "single leg squat (pistol) male": "1759",
  "sissy squat": "1489",
  "sit-up v. 2": "0735",
  "sit-up with arms on chest": "3679",
  "skater hops": "3361",
  "ski ergometer": "2142",
  "ski step": "3671",
  "skin the cat": "3304",
  "sled 45 degrees one leg press": "1425",
  "sled 45° leg press (side pov)": "1463",
  "sled 45в° calf press": "0738",
  "sled 45в° leg press": "0739",
  "sled 45в° leg press (back pov)": "1464",
  "sled 45в° leg wide press": "0740",
  "sled calf press on leg press": "1391",
  "sled closer hack squat": "0741",
  "sled forward angled calf raise": "0742",
  "sled hack squat": "0743",
  "sled lying calf press": "2334",
  "sled lying squat": "0744",
  "sled one leg calf press on leg press": "1392",
  "sledge hammer": "1496",
  "smith back shrug": "0746",
  "smith behind neck press": "0747",
  "smith bench press": "0748",
  "smith bent knee good morning": "0749",
  "smith bent over row": "1359",
  "smith chair squat": "0750",
  "smith close-grip bench press": "0751",
  "smith deadlift": "0752",
  "smith decline bench press": "0753",
  "smith decline reverse-grip press": "0754",
  "smith front squat (clean grip)": "1433",
  "smith full squat": "3281",
  "smith hack squat": "0755",
  "smith hip raise": "0756",
  "smith incline bench press": "0757",
  "smith incline reverse-grip press": "0758",
  "smith incline shoulder raises": "0759",
  "smith leg press": "0760",
  "smith low bar squat": "1434",
  "smith machine bicep curl": "1683",
  "smith machine decline close grip bench press": "1625",
  "smith machine incline tricep extension": "1752",
  "smith machine reverse decline close grip bench press": "1626",
  "smith narrow row": "0761",
  "smith one arm row": "1360",
  "smith one leg floor calf raise": "1393",
  "smith rear delt row": "0762",
  "smith reverse calf raises": "1394",
  "smith reverse grip bent over row": "1361",
  "smith reverse-grip press": "0764",
  "smith seated one leg calf raise": "1395",
  "smith seated shoulder press": "0765",
  "smith seated wrist curl": "1426",
  "smith shoulder press": "0766",
  "smith shrug": "0767",
  "smith single leg split squat": "0768",
  "smith sprint lunge": "0769",
  "smith squat": "0770",
  "smith standing back wrist curl": "0771",
  "smith standing behind head military press": "0772",
  "smith standing leg calf raise": "0773",
  "smith standing military press": "0774",
  "smith sumo squat": "3142",
  "smith toe raise": "1396",
  "smith upright row": "0775",
  "smith wide grip bench press": "1308",
  "smith wide grip decline bench press": "1309",
  "snatch pull": "0776",
  "spell caster": "0777",
  "sphinx": "1362",
  "spider crawl push up": "0778",
  "spine stretch": "1363",
  "spine twist": "2329",
  "split squats": "2368",
  "squat jerk": "0786",
  "squat on bosu ball": "1705",
  "squat to overhead reach": "1685",
  "squat to overhead reach with twist": "1686",
  "stability ball crunch (full range hands behind head)": "2297",
  "stalder press": "3291",
  "standing archer": "3669",
  "standing behind neck press": "0788",
  "standing calf raise (on a staircase)": "1490",
  "standing calves": "1397",
  "standing calves calf stretch": "1398",
  "standing hamstring and calf stretch with strap": "1599",
  "standing lateral stretch": "0794",
  "standing pelvic tilt": "1364",
  "standing single leg curl": "0795",
  "standing wheel rollerout": "0796",
  "star jump (male)": "3223",
  "stationary bike run v. 3": "2138",
  "stationary bike walk": "0798",
  "straddle maltese": "3314",
  "straddle planche": "3298",
  "straight leg outer hip abductor": "1427",
  "superman push-up": "0803",
  "suspended abdominal fallout": "0805",
  "suspended push-up": "0806",
  "suspended reverse crunch": "0807",
  "suspended row": "0808",
  "suspended split squat": "0809",
  "swimmer kicks v. 2 (male)": "3433",
  "swing 360": "3318",
  "three bench dip": "1753",
  "tire flip": "2459",
  "trap bar deadlift": "0811",
  "triceps dip": "0814",
  "triceps dip (bench leg)": "0812",
  "triceps dip (between benches)": "0813",
  "triceps dips floor": "0815",
  "triceps press": "0816",
  "triceps stretch": "0817",
  "tuck crunch": "0871",
  "twin handle parallel grip lat pulldown": "0818",
  "twist hip lift": "1466",
  "twisted leg raise": "2802",
  "twisted leg raise (female)": "2801",
  "two toe touch (male)": "3231",
  "upper back stretch": "1365",
  "upward facing dog": "1366",
  "v-sit on floor": "3420",
  "vertical leg raise (on parallel bars)": "0826",
  "walk elliptical cross trainer": "2141",
  "walking high knees lunge": "3655",
  "walking lunge": "1460",
  "walking on incline treadmill": "3666",
  "walking on stepmill": "2311",
  "weighted bench dip": "0830",
  "weighted close grip chin-up on dip cage": "2987",
  "weighted cossack squats (male)": "3643",
  "weighted crunch": "0832",
  "weighted decline sit-up": "3670",
  "weighted donkey calf raise": "0833",
  "weighted drop push up": "1310",
  "weighted front plank": "2135",
  "weighted front raise": "0834",
  "weighted hanging leg-hip raise": "0866",
  "weighted hyperextension (on stability ball)": "0835",
  "weighted kneeling step with swing": "3641",
  "weighted lunge with swing": "3644",
  "weighted muscle up": "3286",
  "weighted muscle up (on bar)": "3312",
  "weighted one hand pull up": "3290",
  "weighted overhead crunch (on stability ball)": "0840",
  "weighted pull-up": "0841",
  "weighted round arm": "0844",
  "weighted russian twist": "0846",
  "weighted russian twist (legs up)": "0845",
  "weighted russian twist v. 2": "2371",
  "weighted seated bicep curl (on stability ball)": "0847",
  "weighted seated twist (on stability ball)": "0849",
  "weighted side bend (on stability ball)": "0850",
  "weighted sissy squat": "0851",
  "weighted squat": "0852",
  "weighted standing curl": "0853",
  "weighted standing hand squeeze": "0854",
  "weighted straight bar dip": "3313",
  "weighted stretch lunge": "3642",
  "weighted svend press": "0856",
  "weighted three bench dips": "1754",
  "weighted tricep dips": "1755",
  "weighted triceps dip on high parallel bars": "1767",
  "wheel rollerout": "0857",
  "wheel run": "3637",
  "wide grip pull-up": "1429",
  "wide grip rear pull-up": "1367",
  "wide hand push up": "1311",
  "wide-grip chest dip on high parallel bars": "2363",
  "wind sprints": "0858",
  "world greatest stretch": "1604",
  "wrist circles": "1428",
  "wrist rollerer": "0859"
};

export function getCatalogExerciseDbId(nameEn: string): string | undefined {
  return FORMÉ_EXERCISE_DB_IDS[nameEn.trim()];
}
