/** Forme 내장 카탈로그 34종 (constants/exercises.ts 와 동기화) */
const FORMÉ_CATALOG = [
  { nameKo: '벤치프레스', nameEn: 'Bench Press', muscleGroup: 'chest', gear: 'Barbell', searchHint: 'barbell bench press' },
  { nameKo: '인클라인 벤치프레스', nameEn: 'Incline Bench Press', muscleGroup: 'chest', gear: 'Barbell', searchHint: 'barbell incline bench press' },
  { nameKo: '덤벨 플라이', nameEn: 'Dumbbell Fly', muscleGroup: 'chest', gear: 'Dumbbell', searchHint: 'dumbbell fly' },
  { nameKo: '체스트 프레스 머신', nameEn: 'Chest Press Machine', muscleGroup: 'chest', gear: 'Machine', searchHint: 'lever chest press' },
  { nameKo: '푸쉬업', nameEn: 'Push-up', muscleGroup: 'chest', gear: 'Body', searchHint: 'push up' },
  { nameKo: '오버헤드 프레스', nameEn: 'Overhead Press', muscleGroup: 'shoulder', gear: 'Barbell', searchHint: 'barbell overhead press' },
  { nameKo: '사이드 레터럴 레이즈', nameEn: 'Side Lateral Raise', muscleGroup: 'shoulder', gear: 'Dumbbell', searchHint: 'dumbbell lateral raise' },
  { nameKo: '프론트 레이즈', nameEn: 'Front Raise', muscleGroup: 'shoulder', gear: 'Dumbbell', searchHint: 'dumbbell front raise' },
  { nameKo: '리어 델트 플라이', nameEn: 'Rear Delt Fly', muscleGroup: 'shoulder', gear: 'Dumbbell', searchHint: 'dumbbell rear delt fly' },
  { nameKo: '파이크 푸쉬업', nameEn: 'Pike Push-up', muscleGroup: 'shoulder', gear: 'Body', searchHint: 'pike push up' },
  { nameKo: '플레이트 프론트 레이즈', nameEn: 'Plate Front Raise', muscleGroup: 'shoulder', gear: 'Plate', searchHint: 'plate front raise' },
  { nameKo: '밴드 풀 어파트', nameEn: 'Band Pull-apart', muscleGroup: 'shoulder', gear: 'Band', searchHint: 'band pull apart' },
  { nameKo: '데드리프트', nameEn: 'Deadlift', muscleGroup: 'back', gear: 'Barbell', searchHint: 'barbell deadlift' },
  { nameKo: '랫풀다운', nameEn: 'Lat Pulldown', muscleGroup: 'back', gear: 'Machine', searchHint: 'cable pulldown' },
  { nameKo: '바벨 로우', nameEn: 'Barbell Row', muscleGroup: 'back', gear: 'Barbell', searchHint: 'barbell bent over row' },
  { nameKo: '시티드 케이블 로우', nameEn: 'Seated Cable Row', muscleGroup: 'back', gear: 'Machine', searchHint: 'cable seated row' },
  { nameKo: '풀업', nameEn: 'Pull-up', muscleGroup: 'back', gear: 'Body', searchHint: 'pull up' },
  { nameKo: '바벨 컬', nameEn: 'Barbell Curl', muscleGroup: 'arms', gear: 'Barbell', searchHint: 'barbell curl' },
  { nameKo: '덤벨 컬', nameEn: 'Dumbbell Curl', muscleGroup: 'arms', gear: 'Dumbbell', searchHint: 'dumbbell curl' },
  { nameKo: '해머 컬', nameEn: 'Hammer Curl', muscleGroup: 'arms', gear: 'Dumbbell', searchHint: 'dumbbell hammer curl' },
  { nameKo: '트라이셉스 푸쉬다운', nameEn: 'Triceps Pushdown', muscleGroup: 'arms', gear: 'Machine', searchHint: 'triceps pushdown' },
  { nameKo: '딥스', nameEn: 'Dips', muscleGroup: 'arms', gear: 'Body', searchHint: 'triceps dip' },
  { nameKo: '밴드 트라이셉스 푸쉬다운', nameEn: 'Band Triceps Pushdown', muscleGroup: 'arms', gear: 'Band', searchHint: 'band triceps pushdown' },
  { nameKo: '플랭크', nameEn: 'Plank', muscleGroup: 'core', gear: 'Body', searchHint: 'front plank' },
  { nameKo: '행잉 레그 레이즈', nameEn: 'Hanging Leg Raise', muscleGroup: 'core', gear: 'Body', searchHint: 'hanging leg raise' },
  { nameKo: '크런치', nameEn: 'Crunch', muscleGroup: 'core', gear: 'Body', searchHint: 'crunch floor' },
  { nameKo: '러시안 트위스트', nameEn: 'Russian Twist', muscleGroup: 'core', gear: 'Plate', searchHint: 'russian twist' },
  { nameKo: '스쿼트', nameEn: 'Squat', muscleGroup: 'legs', gear: 'Barbell', searchHint: 'barbell squat' },
  { nameKo: '레그 프레스', nameEn: 'Leg Press', muscleGroup: 'legs', gear: 'Machine', searchHint: 'sled leg press' },
  { nameKo: '런지', nameEn: 'Lunge', muscleGroup: 'legs', gear: 'Dumbbell', searchHint: 'dumbbell lunge' },
  { nameKo: '레그 익스텐션', nameEn: 'Leg Extension', muscleGroup: 'legs', gear: 'Machine', searchHint: 'lever leg extension' },
  { nameKo: '레그 컬', nameEn: 'Leg Curl', muscleGroup: 'legs', gear: 'Machine', searchHint: 'lever lying leg curl' },
  { nameKo: '카프 레이즈', nameEn: 'Calf Raise', muscleGroup: 'legs', gear: 'Machine', searchHint: 'lever standing calf raise' },
  { nameKo: '케틀벨 스윙', nameEn: 'Kettlebell Swing', muscleGroup: 'legs', gear: 'Kettlebell', searchHint: 'kettlebell swing' },
];

module.exports = { FORMÉ_CATALOG };
